### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Enderness** [theseazhang/weekly_news#2]
- 有没有打算做个小网站
- 上传文件建一个文件夹放进去，翻到下面好长
- 可以把新一期的放上面
- 内容加上图片更吸引人

**写的不错，祝越来越好**

**Comment by theseazhang** [comment]
感谢你的建议。

目录已调整为最新在前。

个人网站已经有，但是这个还没有放进去，我还在找怎么同步的方法。图片的话我个人不太喜欢，这个周报主要是为记录和传达一些信息。图片会比较费时间，并且周报会同步到微信公众号，微信导入时经常丢图要手动上传，非常费事，所以能不加图片物品都尽量不加。除非某个图片非常重要。
